services:
  db:
    image: postgres:16-alpine
    container_name: postgres_catalog
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: catalog_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - proxy
networks:
  proxy:
    external: true