services:
  ray-head:
    build:
      context: .
      dockerfile: Dockerfile-ray
    container_name: ray-head
    command: >
      ray start 
      --head
      --port=6379
      --dashboard-host=0.0.0.0
      --dashboard-port=8265
      --ray-client-server-port=10001
      --block
    ports:
      - "8265:8265"   # Ray Dashboard
      - "6379:6379"   # Redis communication port
      - "10001:10001" # Ray Client
      # - "52365:52365" # Dashboard agent port
    shm_size: "8gb"
    networks:
      - proxy
    environment:
      - RAY_LOG_TO_STDERR=1
    volumes:
      - ./:/app

  ray-worker:
    build:
      context: .
      dockerfile: Dockerfile-ray
    deploy:
      replicas: 1  # Number of worker replicas
      # resources:
      #   limits:
      #     cpus: "2.0"
      #     memory: "4g"
    command: >
      ray start --address=ray-head:6379 --block --dashboard-agent-listen-port=52365
    depends_on:
      ray-head:
        condition: service_healthy
    shm_size: "8gb"
    networks:
      - proxy
    environment:
      - RAY_LOG_TO_STDERR=1
    volumes:
      - ./:/app

volumes:
  shared_volume:
    driver: local

networks:
  proxy:
    external: true
